name: Main CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Resolve dependencies
      run: mvn dependency:go-offline
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
    - name: Run tests
      run: mvn -B test
      env:
        JAVA_TOOL_OPTIONS: "-Duser.language=pt -Duser.country=BR -Dfile.encofing=UTF-8"
    - name: Add tag
      run: |
          TAG="build-$(date +'%d-%m-%Y/%H-%M-%S')"
          git tag $TAG
          git push origin $TAG
